int Q = 2;
int W = 3;
int E = 4;
int R = 5;
int T = 6;
int Y = 7;
int U = 8;
int I = 9;
int O = 10;
int P = 11;
int A = 12;
int S = 13;
int D = 22;
int F = 23;
int G = 24;
int H = 25;
int J = 26;
int K = 27;
int L = 28;
int Z = 29;
int X = 30;
int C = 31;
int V = 32;
int B = 33;
int N = 34;
int M = 35;



void setup() {
  pinMode(Q, OUTPUT);
  pinMode(W, OUTPUT);
  pinMode(E, OUTPUT);
  pinMode(R, OUTPUT);
  pinMode(T, OUTPUT);
  pinMode(Y, OUTPUT);
  pinMode(U, OUTPUT);
  pinMode(I, OUTPUT);
  pinMode(O, OUTPUT);
  pinMode(P, OUTPUT);
  pinMode(A, OUTPUT);
  pinMode(S, OUTPUT);
  pinMode(D, OUTPUT);
  pinMode(F, OUTPUT);
  pinMode(G, OUTPUT);
  pinMode(H, OUTPUT);
  pinMode(J, OUTPUT);
  pinMode(K, OUTPUT);
  pinMode(L, OUTPUT);
  pinMode(Z, OUTPUT);
  pinMode(X, OUTPUT);
  pinMode(C, OUTPUT);
  pinMode(V, OUTPUT);
  pinMode(B, OUTPUT);
  pinMode(N, OUTPUT);
  pinMode(M, OUTPUT);
  
} 
void loop() {
  digitalWrite(Q, HIGH);
  digitalWrite(W, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(R, HIGH);
  digitalWrite(T, HIGH);
  digitalWrite(Y, HIGH);
  digitalWrite(U, HIGH);
  digitalWrite(I, HIGH);
  digitalWrite(O, HIGH);
  digitalWrite(P, HIGH);
  digitalWrite(A, HIGH);
  digitalWrite(S, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
  digitalWrite(H, HIGH);
  digitalWrite(J, HIGH);
  digitalWrite(K, HIGH);
  digitalWrite(L, HIGH);
  digitalWrite(Z, HIGH);
  digitalWrite(X, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(V, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(N, HIGH);
  digitalWrite(M, HIGH);
  delay(20000);
  digitalWrite(Q, LOW);
  digitalWrite(W, LOW);
  digitalWrite(E, LOW);
  digitalWrite(R, LOW);
  digitalWrite(T, LOW);
  digitalWrite(Y, LOW);
  digitalWrite(U, LOW);
  digitalWrite(I, LOW);
  digitalWrite(O, LOW);
  digitalWrite(P, LOW);
  digitalWrite(A, LOW);
  digitalWrite(S, LOW);
  digitalWrite(D, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, LOW);
  digitalWrite(H, LOW);
  digitalWrite(J, LOW);
  digitalWrite(K, LOW);
  digitalWrite(L, LOW);
  digitalWrite(Z, LOW);
  digitalWrite(X, LOW);
  digitalWrite(C, LOW);
  digitalWrite(V, LOW);
  digitalWrite(B, LOW);
  digitalWrite(N, LOW);
  digitalWrite(M, LOW);
  delay(1000);
  digitalWrite(H, HIGH);
  delay(1000);
  digitalWrite(H, LOW);
  delay(1000);
  digitalWrite(U, HIGH);
  delay(1000);
  digitalWrite(U, LOW);
  delay(1000);
  digitalWrite(M, HIGH);
  delay(1000);
  digitalWrite(M, LOW);
  delay(1000);
  digitalWrite(A, HIGH);
  delay(1000);
  digitalWrite(A, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(I, HIGH);
  delay(1000);
  digitalWrite(I, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(Y, HIGH);
  delay(1000);
  digitalWrite(Y, LOW);
  delay(1000);
  digitalWrite(S, HIGH);
  delay(1000);
  digitalWrite(S, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(A, HIGH);
  delay(1000);
  digitalWrite(A, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(D, HIGH);
  delay(1000);
  digitalWrite(D, LOW);
  delay(1000);
  digitalWrite(S, HIGH);
  delay(1000);
  digitalWrite(S, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(O, HIGH);
  delay(1000);
  digitalWrite(O, LOW);
  delay(1000);
  digitalWrite(B, HIGH);
  delay(1000);
  digitalWrite(B, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(P, HIGH);
  delay(1000);
  digitalWrite(P, LOW);
  delay(1000);
  digitalWrite(R, HIGH);
  delay(1000);
  digitalWrite(R, LOW);
  delay(1000);
  digitalWrite(O, HIGH);
  delay(1000);
  digitalWrite(O, LOW);
  delay(1000);
  digitalWrite(F, HIGH);
  delay(1000);
  digitalWrite(F, LOW);
  delay(1000);
  digitalWrite(O, HIGH);
  delay(1000);
  digitalWrite(O, LOW);
  delay(1000);
  digitalWrite(U, HIGH);
  delay(1000);
  digitalWrite(U, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(D, HIGH);
  delay(1000);
  digitalWrite(D, LOW);
  delay(1000);
  digitalWrite(L, HIGH);
  delay(1000);
  digitalWrite(L, LOW);
  delay(1000);
  digitalWrite(Y, HIGH);
  delay(1000);
  digitalWrite(Y, LOW);
  delay(1000);
  digitalWrite(A, HIGH);
  delay(1000);
  digitalWrite(A, LOW);
  delay(1000);
  digitalWrite(F, HIGH);
  delay(1000);
  digitalWrite(F, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(C, HIGH);
  delay(1000);
  digitalWrite(C, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(D, HIGH);
  delay(1000);
  digitalWrite(D, LOW);
  delay(1000);
  digitalWrite(B, HIGH);
  delay(1000);
  digitalWrite(B, LOW);
  delay(1000);
  digitalWrite(Y, HIGH);
  delay(1000);
  digitalWrite(Y, LOW);
  delay(1000);
  digitalWrite(S, HIGH);
  delay(1000);
  digitalWrite(S, LOW);
  delay(1000);
  digitalWrite(C, HIGH);
  delay(1000);
  digitalWrite(C, LOW);
  delay(1000);
  digitalWrite(I, HIGH);
  delay(1000);
  digitalWrite(I, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(C, HIGH);
  delay(1000);
  digitalWrite(C, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(A, HIGH);
  delay(1000);
  digitalWrite(A, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(D, HIGH);
  delay(1000);
  digitalWrite(D, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(C, HIGH);
  delay(1000);
  digitalWrite(C, LOW);
  delay(1000);
  digitalWrite(H, HIGH);
  delay(1000);
  digitalWrite(H, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(O, HIGH);
  delay(1000);
  digitalWrite(O, LOW);
  delay(1000);
  digitalWrite(L, HIGH);
  delay(1000);
  digitalWrite(L, LOW);
  delay(1000);
  digitalWrite(O, HIGH);
  delay(1000);
  digitalWrite(O, LOW);
  delay(1000);
  digitalWrite(G, HIGH);
  delay(1000);
  digitalWrite(G, LOW);
  delay(1000);
  digitalWrite(Y, HIGH);
  delay(1000);
  digitalWrite(Y, LOW);
  delay(1000);
  digitalWrite(I, HIGH);
  delay(1000);
  digitalWrite(I, LOW);
  delay(1000);
  digitalWrite(N, HIGH);
  delay(1000);
  digitalWrite(N, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(H, HIGH);
  delay(1000);
  digitalWrite(H, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(F, HIGH);
  delay(1000);
  digitalWrite(F, LOW);
  delay(1000);
  digitalWrite(U, HIGH);
  delay(1000);
  digitalWrite(U, LOW);
  delay(1000);
  digitalWrite(T, HIGH);
  delay(1000);
  digitalWrite(T, LOW);
  delay(1000);
  digitalWrite(U, HIGH);
  delay(1000);
  digitalWrite(U, LOW);
  delay(1000);
  digitalWrite(R, HIGH);
  delay(1000);
  digitalWrite(R, LOW);
  delay(1000);
  digitalWrite(E, HIGH);
  delay(1000);
  digitalWrite(E, LOW);
  delay(1000);
  digitalWrite(Q, HIGH);
  digitalWrite(W, HIGH);
  digitalWrite(E, HIGH);
  digitalWrite(R, HIGH);
  digitalWrite(T, HIGH);
  digitalWrite(Y, HIGH);
  digitalWrite(U, HIGH);
  digitalWrite(I, HIGH);
  digitalWrite(O, HIGH);
  digitalWrite(P, HIGH);
  digitalWrite(A, HIGH);
  digitalWrite(S, HIGH);
  digitalWrite(D, HIGH);
  digitalWrite(F, HIGH);
  digitalWrite(G, HIGH);
  digitalWrite(H, HIGH);
  digitalWrite(J, HIGH);
  digitalWrite(K, HIGH);
  digitalWrite(L, HIGH);
  digitalWrite(Z, HIGH);
  digitalWrite(X, HIGH);
  digitalWrite(C, HIGH);
  digitalWrite(V, HIGH);
  digitalWrite(B, HIGH);
  digitalWrite(N, HIGH);
  digitalWrite(M, HIGH);
  delay(3000);
  digitalWrite(Q, LOW);
  digitalWrite(W, LOW);
  digitalWrite(E, LOW);
  digitalWrite(R, LOW);
  digitalWrite(T, LOW);
  digitalWrite(Y, LOW);
  digitalWrite(U, LOW);
  digitalWrite(I, LOW);
  digitalWrite(O, LOW);
  digitalWrite(P, LOW);
  digitalWrite(A, LOW);
  digitalWrite(S, LOW);
  digitalWrite(D, LOW);
  digitalWrite(F, LOW);
  digitalWrite(G, LOW);
  digitalWrite(H, LOW);
  digitalWrite(J, LOW);
  digitalWrite(K, LOW);
  digitalWrite(L, LOW);
  digitalWrite(Z, LOW);
  digitalWrite(X, LOW);
  digitalWrite(C, LOW);
  digitalWrite(V, LOW);
  digitalWrite(B, LOW);
  digitalWrite(N, LOW);
  digitalWrite(M, LOW);
  delay(1000);
  
}


